function add_signature()

txt = {'Atharva Prashant Kale', ...
       'Northeastern ID: 002442878', ...
       'Email: kale.ath@northeastern.edu'};
annotation('textbox', [0.65, 0.01, 0.35, 0.1], ...
    'String', txt, 'FontSize', 8, 'EdgeColor', 'none', ...
    'HorizontalAlignment', 'right', 'Interpreter', 'none');
end